#include "render.h"
#include "gl_loader.h"
#include "platform.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STBI_WRITE_NO_STDIO_FAILURE_CHECK
#include "stb_image_write.h"

/* Embedded GLSL (generated by cmake/embed.cmake). */
extern const char shader_star_vert[], shader_star_frag[], shader_lens_frag[],
    shader_post_vert[], shader_ghost_frag[], shader_blur_frag[], shader_blit_frag[],
    shader_damage_frag[], shader_dust_vert[], shader_bright_frag[],
    shader_binary_frag[];

/* The sky is fixed: the same stars every warp, drawn from the same seed, so a
 * star can be recognised and then watched as the hole smears it into an arc.
 * Nothing about the sky depends on the run. */
#define STAR_SEED 0x5EEDBEEFu
/* Once the ray is out this far the field is too weak to matter. */
#define ESCAPE_R 900.f
/* The Star count setting is stars IN VIEW, which is the number anyone can
 * actually judge, and the number the brief asked for. A 60-degree frame at
 * 16:9 covers 1.465 steradians - 11.66% of the sky - so the sphere has to
 * carry about 8.6 times as many.
 *
 * Spreading the slider's number over the whole sphere instead, which is what
 * this did, put 641 stars in frame when it claimed 5500. A sky that sparse has
 * no depth in it: the eye reads a scattering of separate dots stuck on a
 * backdrop, not a field going away from you forever. */
#define SKY_VIEW_FRACTION 0.1166f

/* Motes in the near field. Enough to read as a medium, few enough that the
 * draw is free next to the lens pass. */
#define DUST_COUNT 900

/* ------------------------------------------------------------------------ */
static unsigned compile(GLenum type, const char *src, const char *name) {
    unsigned sh = glCreateShader(type);
    glShaderSource(sh, 1, &src, NULL);
    glCompileShader(sh);
    GLint ok = 0;
    glGetShaderiv(sh, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char log[2048];
        glGetShaderInfoLog(sh, sizeof log, NULL, log);
        plat_log("shader %s failed:\n%s", name, log);
        glDeleteShader(sh);
        return 0;
    }
    return sh;
}

static unsigned link_program(const char *vs, const char *fs, const char *name) {
    unsigned v = compile(GL_VERTEX_SHADER, vs, name);
    unsigned f = compile(GL_FRAGMENT_SHADER, fs, name);
    if (!v || !f) return 0;
    unsigned p = glCreateProgram();
    glAttachShader(p, v);
    glAttachShader(p, f);
    glLinkProgram(p);
    glDeleteShader(v);
    glDeleteShader(f);
    GLint ok = 0;
    glGetProgramiv(p, GL_LINK_STATUS, &ok);
    if (!ok) {
        char log[2048];
        glGetProgramInfoLog(p, sizeof log, NULL, log);
        plat_log("program %s failed to link:\n%s", name, log);
        glDeleteProgram(p);
        return 0;
    }
    return p;
}

static void set_color(unsigned prog, const char *name, unsigned rgb) {
    glUniform3f(glGetUniformLocation(prog, name),
                ((rgb >> 16) & 255) / 255.f, ((rgb >> 8) & 255) / 255.f, (rgb & 255) / 255.f);
}
static void set1f(unsigned prog, const char *name, float v) {
    glUniform1f(glGetUniformLocation(prog, name), v);
}
static void set1i(unsigned prog, const char *name, int v) {
    glUniform1i(glGetUniformLocation(prog, name), v);
}
static void set3v(unsigned prog, const char *name, vec3 v) {
    glUniform3f(glGetUniformLocation(prog, name), v.x, v.y, v.z);
}
static void draw_fullscreen(void) { glDrawArrays(GL_TRIANGLES, 0, 3); }

/* ------------------------------------------------------------------------ */
Quality render_quality(int setting) {
    float q = clampf(setting / 100.f, 0.f, 1.f);
    Quality out;
    out.steps = (int)lerpf(96.f, 288.f, q);
    out.scale = lerpf(0.50f, 1.00f, q);
    out.cube_face = setting < 40 ? 512 : (setting < 75 ? 1024 : 2048);
    return out;
}

/* --- the star field ------------------------------------------------------ */
/* Six floats per star: direction, magnitude, temperature, twinkle phase. */
#define STAR_STRIDE 6

static void fill_stars(float *v, int n) {
    rng_t rng = { STAR_SEED };
    /* A galactic plane, tilted so it never lines up with the disk or the
     * screen edges. About a third of the stars crowd into it, which is what
     * stops the sky reading as evenly-scattered noise. */
    vec3 gal_n = v3_norm(v3(0.31f, 0.78f, -0.54f));
    vec3 gal_a = v3_norm(v3_cross(gal_n, v3(0, 0, 1)));
    vec3 gal_b = v3_cross(gal_n, gal_a);

    for (int i = 0; i < n; ++i) {
        vec3 d;
        if (rng_f(&rng) < 0.34f) {
            /* in the band: uniform in longitude, tight gaussian-ish in latitude */
            float lon = rng_range(&rng, 0.f, 2.f * BH_PI);
            float lat = (rng_f(&rng) + rng_f(&rng) + rng_f(&rng) - 1.5f) * 0.20f;
            float cl = cosf(lat), sl = sinf(lat);
            d = v3_norm(v3_add(v3_scale(gal_n, sl),
                               v3_add(v3_scale(gal_a, cl * cosf(lon)),
                                      v3_scale(gal_b, cl * sinf(lon)))));
        } else {
            /* uniform on the sphere: z uniform, longitude uniform */
            float z = rng_range(&rng, -1.f, 1.f);
            float t = rng_range(&rng, 0.f, 2.f * BH_PI);
            float s = sqrtf(fmaxf(1.f - z * z, 0.f));
            d = v3(s * cosf(t), z, s * sinf(t));
        }
        /* Realistic magnitudes: the faint ones vastly outnumber the bright.
         * The exponent is what keeps a handful blazing without washing the
         * field out. */
        float mag = powf(rng_f(&rng), 2.0f);
        /* Temperature only shows when natural colours are switched on, but it
         * is generated either way so the sky does not change shape when the
         * setting is toggled. */
        float temp = clampf(0.5f + 0.34f * (rng_f(&rng) + rng_f(&rng) - 1.f) +
                            (rng_f(&rng) < 0.06f ? 0.35f : 0.f), 0.f, 1.f);
        float *o = v + (size_t)i * STAR_STRIDE;
        o[0] = d.x; o[1] = d.y; o[2] = d.z;
        o[3] = mag; o[4] = temp; o[5] = rng_f(&rng);
    }
}

void render_rebuild_stars(Renderer *r, const Settings *s) {
    int n = (int)clampf((float)s->star_count / SKY_VIEW_FRACTION, 64.f, 220000.f);
    float *v = malloc((size_t)n * STAR_STRIDE * sizeof(float));
    if (!v) return;
    fill_stars(v, n);
    glBindVertexArray(r->star_vao);
    glBindBuffer(GL_ARRAY_BUFFER, r->star_vbo);
    glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)n * STAR_STRIDE * sizeof(float), v, GL_STATIC_DRAW);
    const GLsizei stride = STAR_STRIDE * sizeof(float);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, stride, (void *)0);
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 1, GL_FLOAT, GL_FALSE, stride, (void *)(3 * sizeof(float)));
    glEnableVertexAttribArray(2);
    glVertexAttribPointer(2, 1, GL_FLOAT, GL_FALSE, stride, (void *)(4 * sizeof(float)));
    glEnableVertexAttribArray(3);
    glVertexAttribPointer(3, 1, GL_FLOAT, GL_FALSE, stride, (void *)(5 * sizeof(float)));
    glBindVertexArray(r->vao);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    free(v);
    r->star_count = n;
    r->sky_valid = 0;
    plat_log("star field: %d on the sphere (%d in a 60-degree view)",
             n, s->star_count);
}

/* --- the sky cube map ---------------------------------------------------- */
static void build_sky_target(Renderer *r, int face) {
    if (!r->sky_tex) glGenTextures(1, &r->sky_tex);
    glBindTexture(GL_TEXTURE_CUBE_MAP, r->sky_tex);
    for (int i = 0; i < 6; ++i)
        glTexImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, GL_RGBA8, face, face, 0,
                     GL_RGBA, GL_UNSIGNED_BYTE, NULL);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
    if (!r->sky_fbo) glGenFramebuffers(1, &r->sky_fbo);
    r->sky_face = face;
    r->sky_valid = 0;
    glBindTexture(GL_TEXTURE_CUBE_MAP, 0);
}

/* The six 90-degree views, in the cube map's own (left-handed, y-down)
 * convention. Each entry is the face's forward and up direction. */
static const vec3 face_fwd[6] = {
    {  1,  0,  0 }, { -1,  0,  0 }, {  0,  1,  0 },
    {  0, -1,  0 }, {  0,  0,  1 }, {  0,  0, -1 }
};
static const vec3 face_up[6] = {
    {  0, -1,  0 }, {  0, -1,  0 }, {  0,  0,  1 },
    {  0,  0, -1 }, {  0, -1,  0 }, {  0, -1,  0 }
};

static void render_sky(Renderer *r, const Settings *s, float time) {
    glBindFramebuffer(GL_FRAMEBUFFER, r->sky_fbo);
    glViewport(0, 0, r->sky_face, r->sky_face);
    glUseProgram(r->prog_star);
    set1f(r->prog_star, "uPointPx", (float)s->particle_size *
          ((float)r->sky_face / 1024.f));
    set1f(r->prog_star, "uTwinkle", s->twinkle / 100.f);
    set1f(r->prog_star, "uTime", time);
    set1f(r->prog_star, "uNatural", s->natural_star_color ? 1.f : 0.f);
    set_color(r->prog_star, "uColor", s->star_color);

    mat4 proj = m4_perspective(BH_PI * 0.5f, 1.f, 1.f, 10000.f);
    glEnable(GL_BLEND);
    glBlendFunc(GL_ONE, GL_ONE);
    glBindVertexArray(r->star_vao);
    for (int f = 0; f < 6; ++f) {
        glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
                               GL_TEXTURE_CUBE_MAP_POSITIVE_X + f, r->sky_tex, 0);
        glClearColor(((s->space_color >> 16) & 255) / 255.f,
                     ((s->space_color >> 8) & 255) / 255.f,
                     (s->space_color & 255) / 255.f, 1.f);
        glClear(GL_COLOR_BUFFER_BIT);
        mat4 view = m4_look_at(v3(0, 0, 0), face_fwd[f], face_up[f]);
        mat4 vp = m4_mul(proj, view);
        glUniformMatrix4fv(glGetUniformLocation(r->prog_star, "uViewProj"), 1, GL_FALSE, vp.m);
        glDrawArrays(GL_POINTS, 0, r->star_count);
    }
    glDisable(GL_BLEND);
    glBindVertexArray(r->vao);
    glBindTexture(GL_TEXTURE_CUBE_MAP, r->sky_tex);
    glGenerateMipmap(GL_TEXTURE_CUBE_MAP);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    r->sky_valid = 1;
    r->sky_time = time;
}

/* --- offscreen targets --------------------------------------------------- */
static void make_target(unsigned *fbo, unsigned *tex, int w, int h) {
    if (!*tex) glGenTextures(1, tex);
    glBindTexture(GL_TEXTURE_2D, *tex);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, w, h, 0, GL_RGBA, GL_UNSIGNED_BYTE, NULL);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    if (!*fbo) glGenFramebuffers(1, fbo);
    glBindFramebuffer(GL_FRAMEBUFFER, *fbo);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, *tex, 0);
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
        plat_log("framebuffer incomplete (%dx%d)", w, h);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}

static void ensure_targets(Renderer *r) {
    if (r->fbo_w == r->low_w && r->fbo_h == r->low_h && r->tex_scene) return;
    make_target(&r->fbo_scene, &r->tex_scene, r->low_w, r->low_h);
    make_target(&r->fbo_acc[0], &r->tex_acc[0], r->low_w, r->low_h);
    make_target(&r->fbo_acc[1], &r->tex_acc[1], r->low_w, r->low_h);
    make_target(&r->fbo_tmp, &r->tex_tmp, r->low_w, r->low_h);
    /* The glow runs at half resolution. By the time it is blurred it is all
     * low frequency anyway, so nobody can tell, and it makes the whole chain
     * nearly free. */
    r->bloom_w = r->low_w / 2 > 1 ? r->low_w / 2 : 1;
    r->bloom_h = r->low_h / 2 > 1 ? r->low_h / 2 : 1;
    make_target(&r->fbo_bloom[0], &r->tex_bloom[0], r->bloom_w, r->bloom_h);
    make_target(&r->fbo_bloom[1], &r->tex_bloom[1], r->bloom_w, r->bloom_h);
    r->fbo_w = r->low_w;
    r->fbo_h = r->low_h;
    r->acc_valid = 0;
}

void render_resize(Renderer *r, int w, int h) {
    r->width = w > 1 ? w : 1;
    r->height = h > 1 ? h : 1;
    int lw = (int)((float)r->width * r->q.scale + 0.5f);
    int lh = (int)((float)r->height * r->q.scale + 0.5f);
    r->low_w = lw > 1 ? lw : 1;
    r->low_h = lh > 1 ? lh : 1;
}

/* ------------------------------------------------------------------------ */
int render_init(Renderer *r, const Settings *s) {
    memset(r, 0, sizeof *r);
    r->q = render_quality(s->quality > 0 ? s->quality : 55);
    r->prog_star  = link_program(shader_star_vert, shader_star_frag, "star");
    r->prog_lens  = link_program(shader_post_vert, shader_lens_frag, "lens");
    r->prog_ghost = link_program(shader_post_vert, shader_ghost_frag, "ghost");
    r->prog_blur  = link_program(shader_post_vert, shader_blur_frag, "blur");
    r->prog_blit  = link_program(shader_post_vert, shader_blit_frag, "blit");
    r->prog_damage = link_program(shader_post_vert, shader_damage_frag, "damage");
    r->prog_dust   = link_program(shader_dust_vert, shader_star_frag, "dust");
    r->prog_bright = link_program(shader_post_vert, shader_bright_frag, "bright");
    r->prog_binary = link_program(shader_post_vert, shader_binary_frag, "binary");
    if (!r->prog_star || !r->prog_lens || !r->prog_ghost || !r->prog_blur ||
        !r->prog_blit || !r->prog_damage || !r->prog_dust || !r->prog_bright ||
        !r->prog_binary)
        return 0;

    /* Core profile needs a VAO bound even with no attributes. */
    glGenVertexArrays(1, &r->vao);
    glGenVertexArrays(1, &r->star_vao);
    glGenBuffers(1, &r->star_vbo);
    glBindVertexArray(r->vao);
    render_rebuild_stars(r, s);
    build_sky_target(r, r->q.cube_face);

    /* Some drivers reject this query in a core profile; fall back to 64 px. */
    while (glGetError() != GL_NO_ERROR) {}
    GLfloat range[2] = { 1.f, 64.f };
    glGetFloatv(GL_ALIASED_POINT_SIZE_RANGE, range);
    if (glGetError() != GL_NO_ERROR) range[1] = 64.f;
    r->max_point_px = range[1] < 8.f ? 8.f : (range[1] > 256.f ? 256.f : range[1]);

    glGenQueries(3, r->gpu_query);
    r->query_ok = 1;
    while (glGetError() != GL_NO_ERROR) {}

    glEnable(GL_PROGRAM_POINT_SIZE);
    glDisable(GL_DEPTH_TEST);
    glDisable(GL_CULL_FACE);
    plat_log("GL %s / %s, max point %.0f px; quality: %d steps, scale %.2f, cube %d",
             (const char *)glGetString(GL_RENDERER), (const char *)glGetString(GL_VERSION),
             r->max_point_px, r->q.steps, r->q.scale, r->q.cube_face);
    gl_check("render_init");
    return 1;
}

/* Reads back whichever timer query has finished, and starts a new one. Three
 * in rotation, so a result is always a couple of frames old and the read never
 * stalls the pipeline waiting for the GPU to catch up. */
static void gpu_timer_begin(Renderer *r) {
    if (!r->query_ok) return;
    int slot = r->query_slot;
    int read = (slot + 1) % 3;
    if (r->query_live[read]) {
        GLuint ready = 0;
        glGetQueryObjectuiv(r->gpu_query[read], GL_QUERY_RESULT_AVAILABLE, &ready);
        if (ready) {
            GLuint64 ns = 0;
            glGetQueryObjectui64v(r->gpu_query[read], GL_QUERY_RESULT, &ns);
            r->query_live[read] = 0;
            if (ns > 0) r->last_frame_ms = (float)ns / 1e6f;
        }
    }
    glBeginQuery(GL_TIME_ELAPSED, r->gpu_query[slot]);
    if (glGetError() != GL_NO_ERROR) { r->query_ok = 0; return; }
    r->query_live[slot] = 1;
}

static void gpu_timer_end(Renderer *r) {
    if (!r->query_ok) return;
    glEndQuery(GL_TIME_ELAPSED);
    r->query_slot = (r->query_slot + 1) % 3;
}

void render_frame(Renderer *r, const Settings *s, const Scene *sc, float time, float dt) {
    gpu_timer_begin(r);
    const int want_ghost = s->ghost_tail > 0;
    const int want_blur  = s->blur > 0;

    if (r->sky_face != r->q.cube_face) build_sky_target(r, r->q.cube_face);
    ensure_targets(r);

    /* The sky only has to be redrawn when something about it changes. With
     * twinkle off and the stars fixed, that is once - and even with twinkle on
     * it is throttled: a full sky is a quarter of a million sprites across six
     * faces, and nobody can see a star flicker faster than this anyway. */
    if (!r->sky_valid) render_sky(r, s, time);
    else if (s->twinkle > 0 && time - r->sky_time > 1.f / 24.f) render_sky(r, s, time);

    /* --- the lens pass ---------------------------------------------------- */
    glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_scene);
    glViewport(0, 0, r->low_w, r->low_h);
    /* One hole collapses to a single ODE in the plane the ray lies in, which
     * is cheap. Two do not lie in any plane at all, so the pair gets a full
     * three-dimensional march of its own rather than slowing the common case
     * down with a branch it never takes. */
    unsigned lens = sc->binary ? r->prog_binary : r->prog_lens;
    glUseProgram(lens);
    glBindVertexArray(r->vao);
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_CUBE_MAP, r->sky_tex);
    set1i(lens, "uStars", 0);

    vec3 pos = scene_cam_pos(sc), right, up, fwd;
    scene_cam_basis(sc, &right, &up, &fwd);
    float basis[9] = { right.x, right.y, right.z, up.x, up.y, up.z, fwd.x, fwd.y, fwd.z };
    set3v(lens, "uCamPos", pos);
    glUniformMatrix3fv(glGetUniformLocation(lens, "uCamBasis"), 1, GL_FALSE, basis);
    set1f(lens, "uTanHalfFov", tanf(sc->fov * 0.5f));
    set1f(lens, "uAspect", (float)r->width / (float)r->height);
    set1i(lens, "uSteps", r->q.steps);
    set1f(lens, "uLensing", sc->lensing);
    /* The pair is marched in three dimensions, so it pays per step: it is
     * let go as soon as the field is too weak to bend anything. */
    set1f(lens, "uEscapeR", sc->binary ? 320.f : ESCAPE_R);
    /* The mip level has to be chosen here, since the shader cannot work it out
     * from its own derivatives. One screen pixel subtends this much sky; the
     * cube map has this much resolution. Where the shot is wide and the stars
     * are crowded into few pixels, a higher level stops them scintillating. */
    {
        float px_rad = 2.f * tanf(sc->fov * 0.5f) / (float)r->low_h;
        float texel_rad = (BH_PI * 0.5f) / (float)r->sky_face;
        /* One stop sharper than strict anti-aliasing asks for. Stars are
         * point sources: softening one to kill its aliasing does not give a
         * cleaner star, it gives a smudge, and a sky full of smudges reads as
         * texture stuck on a wall rather than as lights at infinity. A little
         * scintillation is the honest trade, and the ghost tail hides it. */
        float lod = log2f(fmaxf(px_rad / texel_rad, 1.f)) - 1.f;
        set1f(lens, "uSkyLod", clampf(lod, 0.f, 5.f));
    }

    set3v(lens, "uDiskNormal", sc->axis);
    set3v(lens, "uDiskX", sc->disk_x);
    set3v(lens, "uDiskY", sc->disk_y);
    set1i(lens, "uDiskMode", sc->disk_mode);
    set1f(lens, "uOuterReach", sc->outer_reach);
    set1f(lens, "uStarR", sc->star_r);
    set1f(lens, "uStarAz", sc->star_az);
    set1f(lens, "uStreamWind", sc->stream_wind);
    if (sc->binary) {
        set3v(lens, "uHoleA", sc->hole_a);
        set3v(lens, "uHoleB", sc->hole_b);
        set1f(lens, "uMassA", sc->mass_a);
        set1f(lens, "uMassB", sc->mass_b);
    }
    set1f(lens, "uDiskInner", sc->disk_inner);
    set1f(lens, "uDiskOuter", sc->disk_outer);
    set1f(lens, "uDiskBright", sc->disk_bright);
    set1f(lens, "uDiskTime", sc->disk_time);
    set1i(lens, "uDoppler", s->doppler);
    set1f(lens, "uRedshift", s->redshift ? 1.f : 0.f);
    set1f(lens, "uRingGlow", sc->ring_glow);
    set_color(lens, "uDiskColor", s->disk_color);
    set_color(lens, "uRingColor", s->ring_color);
    set_color(lens, "uShadowColor", s->shadow_color);
    set1f(lens, "uBoost", sc->boost);
    set3v(lens, "uBoostDir", scene_boost_dir(sc));
    set1f(lens, "uDiskShear", sc->disk_shear);
    draw_fullscreen();

    /* --- the near field ---------------------------------------------------
     * Dust motes a few tens of units out, drawn over the finished lens image.
     * They are not lensed: at this range the deflection is far too small to
     * see, and paying for it per mote would buy nothing. They are here to do
     * the one job the hole cannot - show that the camera is moving. */
    {
        unsigned p = r->prog_dust;
        mat4 view = m4_look_at(pos, v3_add(pos, fwd), up);
        mat4 proj = m4_perspective(sc->fov, (float)r->width / (float)r->height, 0.05f, 4000.f);
        mat4 vp = m4_mul(proj, view);
        float proj_scale = (float)r->low_h * 0.5f * proj.m[5];
        glEnable(GL_BLEND);
        glBlendFunc(GL_ONE, GL_ONE);
        glUseProgram(p);
        glUniformMatrix4fv(glGetUniformLocation(p, "uViewProj"), 1, GL_FALSE, vp.m);
        set3v(p, "uCamPos", pos);
        set3v(p, "uTravel", sc->travel);
        set1f(p, "uCell", DUST_CELL);
        set1f(p, "uSpeed", clampf(sc->speed / MOVE_SPEED_MAX, 0.f, 1.f));
        set_color(p, "uColor", s->star_color);
        set1f(p, "uPointWorld", 0.012f * (float)s->particle_size);
        set1f(p, "uProjScale", proj_scale);
        set1f(p, "uMaxPointPx", r->max_point_px);
        glDrawArrays(GL_POINTS, 0, DUST_COUNT);
        glDisable(GL_BLEND);
    }

    /* --- the glow ----------------------------------------------------------
     * Bright-pass, blur, add back. It runs before the ghost tails so the glow
     * smears with them rather than being painted on afterwards, and it is what
     * turns the disk from something orange into something you would not want
     * to be near: the light spills past its own outline and floods the frame,
     * the way anything that bright does to a real lens. */
    if (s->bloom > 0) {
        float strength = s->bloom / 100.f;
        glViewport(0, 0, r->bloom_w, r->bloom_h);
        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_bloom[0]);
        glUseProgram(r->prog_bright);
        glBindTexture(GL_TEXTURE_2D, r->tex_scene);
        set1i(r->prog_bright, "uTex", 0);
        /* A low threshold on purpose: the disk is meant to bloom almost
         * everywhere, not only at its very hottest. */
        set1f(r->prog_bright, "uThreshold", lerpf(0.88f, 0.58f, strength));
        set1f(r->prog_bright, "uKnee", 0.22f);
        draw_fullscreen();

        /* Two separable passes, widening each time, for a glow that reaches
         * well across the frame instead of hugging the disk. */
        glUseProgram(r->prog_blur);
        set1i(r->prog_blur, "uTex", 0);
        for (int pass = 0; pass < 2; ++pass) {
            float rad = (pass == 0 ? 2.0f : 5.0f) * lerpf(0.6f, 1.5f, strength);
            glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_bloom[1]);
            glBindTexture(GL_TEXTURE_2D, r->tex_bloom[0]);
            glUniform2f(glGetUniformLocation(r->prog_blur, "uStep"),
                        rad / (float)r->bloom_w, 0.f);
            draw_fullscreen();
            glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_bloom[0]);
            glBindTexture(GL_TEXTURE_2D, r->tex_bloom[1]);
            glUniform2f(glGetUniformLocation(r->prog_blur, "uStep"),
                        0.f, rad / (float)r->bloom_h);
            draw_fullscreen();
        }

        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_scene);
        glViewport(0, 0, r->low_w, r->low_h);
        glEnable(GL_BLEND);
        glBlendFunc(GL_ONE, GL_ONE);
        glUseProgram(r->prog_blit);
        glBindTexture(GL_TEXTURE_2D, r->tex_bloom[0]);
        set1i(r->prog_blit, "uTex", 0);
        draw_fullscreen();
        glDisable(GL_BLEND);
    }

    /* --- post: ghost tails ------------------------------------------------ */
    unsigned src_tex = r->tex_scene;
    if (want_ghost) {
        /* The warp holds a far longer streak than the slider's longest, the
         * way The Black Wall does while the wall has swept over the camera. */
        float base = lerpf(0.80f, 0.975f, s->ghost_tail / 100.f);
        if (sc->boost > 0.05f) base = lerpf(base, 0.992f, clampf(sc->boost, 0.f, 1.f));
        float decay = powf(base, dt * 60.f);
        int cur = r->acc_index, prev = cur ^ 1;
        if (!r->acc_valid) { decay = 0.f; r->acc_valid = 1; }
        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_acc[cur]);
        glUseProgram(r->prog_ghost);
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, r->tex_scene);
        set1i(r->prog_ghost, "uCurrent", 0);
        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_2D, r->tex_acc[prev]);
        set1i(r->prog_ghost, "uPrevious", 1);
        set1f(r->prog_ghost, "uDecay", decay);
        set1f(r->prog_ghost, "uInvert", 0.f);
        draw_fullscreen();
        glActiveTexture(GL_TEXTURE0);
        src_tex = r->tex_acc[cur];
        r->acc_index = prev;
    }

    /* --- post: blur ------------------------------------------------------- */
    if (want_blur) {
        float radius = (s->blur / 100.f) * 7.f * ((float)r->low_h / 1080.f);
        if (radius < 0.5f) radius = 0.5f;
        glUseProgram(r->prog_blur);
        set1i(r->prog_blur, "uTex", 0);
        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_tmp);
        glViewport(0, 0, r->low_w, r->low_h);
        glBindTexture(GL_TEXTURE_2D, src_tex);
        glUniform2f(glGetUniformLocation(r->prog_blur, "uStep"),
                    radius / 4.f / (float)r->low_w, 0.f);
        draw_fullscreen();
        glBindFramebuffer(GL_FRAMEBUFFER, r->fbo_scene);
        glBindTexture(GL_TEXTURE_2D, r->tex_tmp);
        glUniform2f(glGetUniformLocation(r->prog_blur, "uStep"),
                    0.f, radius / 4.f / (float)r->low_h);
        draw_fullscreen();
        src_tex = r->tex_scene;
    }

    /* --- to the screen, upscaling from the offscreen resolution ----------- */
    /* Camera damage is the one pass that runs at the window's own resolution:
     * a dead pixel has to be one screen pixel, and a crack has to be as sharp
     * as the glass it is in. Upscaling either would give the whole effect
     * away. */
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glViewport(0, 0, r->width, r->height);
    int hurt = sc->dmg_glass > 0.002f || sc->dmg_matrix > 0.002f ||
               sc->dmg_bloom > 0.002f || sc->dmg_tear > 0.002f;
    if (hurt) {
        unsigned p = r->prog_damage;
        glUseProgram(p);
        glBindTexture(GL_TEXTURE_2D, src_tex);
        set1i(p, "uTex", 0);
        glUniform2f(glGetUniformLocation(p, "uResolution"), (float)r->width, (float)r->height);
        set1f(p, "uTime", time);
        set1f(p, "uGlass", sc->dmg_glass);
        set1f(p, "uMatrix", sc->dmg_matrix);
        set1f(p, "uBloom", sc->dmg_bloom);
        set1f(p, "uTear", sc->dmg_tear);
        set_color(p, "uDeadColor", settings_damage_rgb(s));
        set1f(p, "uGreenPurple", s->damage_palette == DMG_GREEN_PURPLE ? 1.f : 0.f);
        glUniform2f(glGetUniformLocation(p, "uImpact"), sc->dmg_impact_x, sc->dmg_impact_y);
    } else {
        glUseProgram(r->prog_blit);
        glBindTexture(GL_TEXTURE_2D, src_tex);
        set1i(r->prog_blit, "uTex", 0);
    }
    draw_fullscreen();
    gpu_timer_end(r);
#ifdef BH_DEBUG
    gl_check("render_frame");
#endif
}

void render_shutdown(Renderer *r) {
    if (r->prog_star) glDeleteProgram(r->prog_star);
    if (r->prog_lens) glDeleteProgram(r->prog_lens);
    if (r->prog_ghost) glDeleteProgram(r->prog_ghost);
    if (r->prog_blur) glDeleteProgram(r->prog_blur);
    if (r->prog_blit) glDeleteProgram(r->prog_blit);
    if (r->prog_damage) glDeleteProgram(r->prog_damage);
    if (r->prog_dust) glDeleteProgram(r->prog_dust);
    if (r->prog_bright) glDeleteProgram(r->prog_bright);
    if (r->prog_binary) glDeleteProgram(r->prog_binary);
    if (r->star_vbo) glDeleteBuffers(1, &r->star_vbo);
    if (r->star_vao) glDeleteVertexArrays(1, &r->star_vao);
    if (r->vao) glDeleteVertexArrays(1, &r->vao);
    if (r->gpu_query[0]) glDeleteQueries(3, r->gpu_query);
    if (r->sky_tex) glDeleteTextures(1, &r->sky_tex);
    if (r->sky_fbo) glDeleteFramebuffers(1, &r->sky_fbo);
    unsigned texs[6] = { r->tex_scene, r->tex_acc[0], r->tex_acc[1], r->tex_tmp,
                         r->tex_bloom[0], r->tex_bloom[1] };
    unsigned fbos[6] = { r->fbo_scene, r->fbo_acc[0], r->fbo_acc[1], r->fbo_tmp,
                         r->fbo_bloom[0], r->fbo_bloom[1] };
    glDeleteTextures(6, texs);
    glDeleteFramebuffers(6, fbos);
    memset(r, 0, sizeof *r);
}

int render_dump_png(const Renderer *r, const char *path) {
    int w = r->width, h = r->height;
    unsigned char *px = malloc((size_t)w * h * 4);
    if (!px) return 0;
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, px);
    /* OpenGL rows start at the bottom; PNG rows at the top. */
    for (int y = 0; y < h / 2; ++y) {
        unsigned char *a = px + (size_t)y * w * 4, *b = px + (size_t)(h - 1 - y) * w * 4;
        for (int i = 0; i < w * 4; ++i) { unsigned char t = a[i]; a[i] = b[i]; b[i] = t; }
    }
    for (size_t i = 3; i < (size_t)w * h * 4; i += 4) px[i] = 255;
    int ok = stbi_write_png(path, w, h, 4, px, w * 4);
    free(px);
    return ok;
}
